/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FlipList;
import java.sql.*;
import javax.swing.JTable;
/**
 *
 * @author USER
 */
public class Page extends javax.swing.JFrame {

    /**
     * Creates new form Page
     */
    public Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        listTitle = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listDescription = new javax.swing.JTextArea();
        listButton = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        listDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        userLogout = new javax.swing.JButton();
        listStat = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("Create New List");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 80, 130, 17);

        listTitle.setText("List Title");
        listTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listTitleActionPerformed(evt);
            }
        });
        jPanel1.add(listTitle);
        listTitle.setBounds(20, 100, 250, 30);

        listDescription.setColumns(20);
        listDescription.setRows(5);
        listDescription.setText("List Description");
        jScrollPane1.setViewportView(listDescription);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 140, 250, 100);

        listButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        listButton.setText("Save");
        listButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listButtonMouseClicked(evt);
            }
        });
        listButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listButtonActionPerformed(evt);
            }
        });
        jPanel1.add(listButton);
        listButton.setBounds(200, 250, 70, 30);

        jTextField2.setText("Search List");
        jPanel1.add(jTextField2);
        jTextField2.setBounds(510, 10, 190, 30);

        jButton2.setText("Search");
        jPanel1.add(jButton2);
        jButton2.setBounds(700, 10, 80, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(280, 18, 220, 20);

        listDate.setText("Date");
        jPanel1.add(listDate);
        listDate.setBounds(20, 250, 170, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 102));
        jLabel4.setText("More");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 430, 50, 17);

        jButton6.setText("Todays Lists");
        jPanel1.add(jButton6);
        jButton6.setBounds(20, 370, 250, 23);

        jButton7.setText("Yesterday Lists");
        jPanel1.add(jButton7);
        jButton7.setBounds(20, 400, 250, 23);

        jButton9.setText("All Lists");
        jPanel1.add(jButton9);
        jButton9.setBounds(20, 340, 250, 23);

        userLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlipList/logout.png"))); // NOI18N
        userLogout.setText("LogOut");
        userLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userLogoutMouseClicked(evt);
            }
        });
        jPanel1.add(userLogout);
        userLogout.setBounds(70, 460, 200, 30);

        listStat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        listStat.setForeground(new java.awt.Color(255, 255, 102));
        jPanel1.add(listStat);
        listStat.setBounds(20, 290, 250, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "This Week", "This Month", "This Year", "Previous Year" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(70, 430, 200, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Recent To Do Lists:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(300, 90, 460, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 102));
        jLabel7.setText("Explore >>");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 310, 130, 17);

        listTable.setModel(new javax.swing.table.DefaultTableModel(

            new Object [][] {
                {"Study", "Math", "25-12-2014"},
                //        {null, null, null},
                //        {null, null, null},
                //        {null, null, null}
            },
            new String [] {
                "List Title", "Description", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(listTable);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(290, 120, 480, 460);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FlipList/page.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 810, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listTitleActionPerformed

    private void listButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listButtonActionPerformed

    private void userLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userLogoutMouseClicked
        WelcomeForm wc = new WelcomeForm();
        wc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_userLogoutMouseClicked

    private void listButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listButtonMouseClicked
        String title = listTitle.getText();
        String description = listDescription.getText();
        String date = listDate.getText();
        Database db = new Database();
        String res = db.insert("INSERT INTO lists (title, description, date) VALUES ('" + title + "', '" + description + "','" + date + "')");

        if (res.equals("true")) {
            this.listStat.setText("List has saved");
        } else {
            this.listStat.setText(res);
        }
    }//GEN-LAST:event_listButtonMouseClicked

    //listTable
    TableHelper newTable = new TableHelper();
//    newTable.fillTable(listTable);
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton listButton;
    private javax.swing.JTextField listDate;
    private javax.swing.JTextArea listDescription;
    private javax.swing.JLabel listStat;
    private javax.swing.JTable listTable;
    private javax.swing.JTextField listTitle;
    private javax.swing.JButton userLogout;
    // End of variables declaration//GEN-END:variables
}
